media: assets/images

content:
  - name: site_data
    label: Site data
    type: group
    items:
      - name: front_page_carousel
        label: Front page carousel
        type: file
        path: data/front-page-carousel.csv

      - name: front_page_breaking_news
        label: Front page breaking news
        type: file
        path: data/front-page-breaking-news.csv

      - name: programs
        label: Programs
        type: file
        path: data/programs.csv

      - name: members
        label: Members
        type: file
        path: data/members.csv

      - name: committee_members
        label: Committee members
        type: file
        path: data/committee-members-members.csv

      - name: committees
        label: Committees
        type: file
        path: data/committee-members-committees.csv

      - name: archive
        label: Archive
        type: file
        path: data/archive.csv

      - name: zero_at_fault_damages
        label: Zero at fault damages
        type: file
        path: assets/zerodamages.csv
